# Generated by Django 3.2.10 on 2022-02-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crnn_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto1', models.CharField(max_length=50)),
                ('crypto2', models.CharField(max_length=50)),
                ('crypto3', models.CharField(max_length=50)),
                ('predict_days', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('num_layer', models.IntegerField()),
                ('hidden_size', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('weight_decay', models.FloatField()),
                ('epoch', models.FloatField()),
                ('n1', models.FloatField(null=True)),
                ('n2', models.FloatField(null=True)),
                ('n3', models.FloatField(null=True)),
                ('Test_error', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='lstm_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto1', models.CharField(max_length=50)),
                ('crypto2', models.CharField(max_length=50)),
                ('crypto3', models.CharField(max_length=50)),
                ('predict_days', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('num_layer', models.IntegerField()),
                ('hidden_size', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('weight_decay', models.FloatField()),
                ('epoch', models.FloatField()),
                ('Test_error', models.FloatField()),
            ],
        ),
    ]
